name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      login:
        description: 'Логин для авторизации'
        required: true
      password:
        description: 'Пароль для авторизации'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file from inputs or secrets
        run: |
          echo "REACT_APP_LOGIN=${{ github.event.inputs.login || secrets.REACT_APP_LOGIN }}" >> .env
          echo "REACT_APP_PASSWORD=${{ github.event.inputs.password || secrets.REACT_APP_PASSWORD }}" >> .env

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 